### ISSUE TITLE
关于秒退

### ISSUE THREAD

**Issue by silent-wind1** [buzhiy/SkipCourse#1]
它刷一会就闪退，这个问题怎么解决, 我的操作系统是win11,文件位置放在桌面上

**Comment by wxm78** [comment]
同问，路径没有中文，
![image](https://github.com/Cuttlef/SkipCourse/assets/81608551/ece6b559-0835-4bdc-8cce-01a9b529dd0c)

**Comment by 10san** [comment]
同问，闪退，并没有刷成功

**Comment by Cuttlef** [comment]
秒退 是是因为 授权码过期了
